# Copyright (c) 2020 NVIDIA CORPORATION. All rights reserved.

all: countersextractor

countersextractor:
	cd cmd/countersextractor; go build countersextractor.go

clean:
	@rm -f cmd/countersextractor/countersextractor